apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nexusai.fullname" . }}-manager-role
  labels:
  {{- include "nexusai.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  - apiextensions.k8s.io
  - apps
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - apps.edgexr.org
  resources:
  - inferencestacks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.edgexr.org
  resources:
  - inferencestacks/finalizers
  verbs:
  - update
- apiGroups:
  - apps.edgexr.org
  resources:
  - inferencestacks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - '*'
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nexusai.fullname" . }}-manager-rolebinding
  labels:
  {{- include "nexusai.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "nexusai.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "nexusai.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'