apiVersion: apps.edgexr.org/v1alpha1
kind: InferenceStack
metadata:
  name: {{ include "nexusai.fullname" . }}-rag-stack
  labels:
  {{- include "nexusai.labels" . | nindent 4 }}
spec:
  llmModel: {{ .Values.inferenceStack.llmModel }}
  minioAccessKey: {{ .Values.inferenceStack.minioAccessKey }}
  minioSecretKey: {{ .Values.inferenceStack.minioSecretKey }}
  storageClassName: {{ .Values.inferenceStack.storageClassName }}
  gpuCount: {{ .Values.inferenceStack.gpuCount }}
  vectorDbPort: {{ .Values.inferenceStack.vectorDbPort }}
